# Generated by Django 4.2.2 on 2023-06-10 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('coordinator', 'Coordinator')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('pass_hash', models.CharField(max_length=128)),
            ],
        ),
    ]
